import React, { Component } from "react";

export default class Wallpapers extends Component {
  render() {
    return (
      <div>
        <p className="subtitle">Here's some of my digital work.</p>
        <p>These are free to download, though donations are appreciated!</p>
        <div className="image-gallery-wrapper">
          <img
            src="https://i1.lensdump.com/i/RJgFr3.png"
            alt="RJgFr3.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgPXF.png"
            alt="RJgPXF.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i3.lensdump.com/i/RJgNlr.png"
            alt="RJgNlr.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgDk7.jpeg"
            alt="RJgDk7.jpeg"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i3.lensdump.com/i/RJgoGb.jpeg"
            alt="RJgoGb.jpeg"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i1.lensdump.com/i/RJgYLT.png"
            alt="RJgYLT.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i2.lensdump.com/i/RJgM9z.png"
            alt="RJgM9z.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgLW5.jpeg"
            alt="RJgLW5.jpeg"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i3.lensdump.com/i/RJgnNC.png"
            alt="RJgnNC.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i2.lensdump.com/i/RJge3v.png"
            alt="RJge3v.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgSr2.png"
            alt="RJgSr2.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i3.lensdump.com/i/RJglX9.png"
            alt="RJglX9.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i1.lensdump.com/i/RJgHHo.png"
            alt="RJgHHo.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgOki.png"
            alt="RJgOki.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i1.lensdump.com/i/RJgpGm.jpeg"
            alt="RJgpGm.jpeg"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgKvP.png"
            alt="RJgKvP.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i1.lensdump.com/i/RJg49Z.png"
            alt="RJg49Z.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i3.lensdump.com/i/RJg3WK.png"
            alt="RJg3WK.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i1.lensdump.com/i/RJgmDc.png"
            alt="RJgmDc.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i3.lensdump.com/i/RJgB31.png"
            alt="RJgB31.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgqgH.png"
            alt="RJgqgH.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i2.lensdump.com/i/RJg9cx.png"
            alt="RJg9cx.png"
            border="0"
            loading="lazy"
          />
          <img
            src="https://i.lensdump.com/i/RJgVHk.png"
            alt="RJgVHk.png"
            border="0"
            loading="lazy"
          />
        </div>
      </div>
    );
  }
}
